## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/SCS.jl.git")'
## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("MathOptInterfaceSCS"); Pkg.test("MathOptInterfaceSCS"; coverage=true)'

before_script:
  - julia -e 'Pkg.add("Compat")'
  - julia -e 'Pkg.checkout("Compat")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterface.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterfaceTests.jl.git")'
  - julia -e 'Pkg.add("SCS")'
  - julia -e 'Pkg.checkout("SCS")'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("MathOptInterfaceSCS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MathOptInterfaceSCS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
